spring:
  datasource:
    urL: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console


resilience4j:
  retry:
    instances:
      eventPredicate:
        maxRetryAttempts: 3
        resultPredicate: com.work.supplement.retry.sample.ConditionPredicate
        waitDuration: 5s

